### ISSUE TITLE
Doesn't agree with Google Authenticator

### ISSUE THREAD

**Issue by blalor** [speakeasyjs/speakeasy#20]
I'm unable to get this to agree with Google Authenticator.  [onceler](https://npmjs.org/package/onceler) does, however.  The `otp` var generated by the two samples below should be equal.  The one from `onceler` agrees with the Google Authenticator app on my iPhone, but speakeasy does not.
## onceler

``` js
var TOKEN = get_token_used_by_google_authenticator();
var TOTP = require("onceler").TOTP;

var otp = (new TOTP(TOKEN)).now();
```
## speakeasy

``` js
var TOKEN = get_token_used_by_google_authenticator();
var speakeasy = require("speakeasy")

var otp = speakeasy.totp({key: TOKEN});
```

**Comment by sachinra** [comment]
the problem I am facing is with BASE32 decoding. 
The Link : https://code.google.com/p/google-authenticator/wiki/KeyUriFormat
The Key : JBSWY3DPEHPK3PXP
otherwise works with any other generated Base32 based on ASCII charset,

**Comment by abdurrachman-habibi** [comment]
+1 @sashimizakana It's fixed by updating thirty-two to 0.0.2

**Comment by crbanman** [comment]
+1 @sashimizakana this fixed the issue for me as well.

**Comment by knoxcard** [comment]
Close the issue?

**Comment by markbao** [comment]
@sashimizakana Thank you for looking into this, and thanks @knoxcard for the ping.

Speakeasy 2.0 no longer depends on thirty-two, and it now depends on [base32.js](https://www.npmjs.com/package/base32.js). I haven't seen these issues on Speakeasy 2.0.

If you're seeing this issue, you can

- Update to thirty-two 0.0.2 as suggested by @sashimizakana.
- Upgrade to Speakeasy 2.0, which is API-compatible with 1.x.

Feel free to comment if you have any other issues.

**Comment by Celadora** [comment]
I am using speakeasy 2.0.0 and having this issue as well. In the browser, it works fine, but if I run it under nodejs it gives the wrong code - which isn't merely a few minutes off. The timezone on my PC and on my server are the same. Google Authenticator is up to date as well.
