### ISSUE TITLE
Howto add label to QR image URL?

### ISSUE THREAD

**Issue by ovaris** [speakeasyjs/speakeasy#39]
I tried several formats for name parameter for adding "label" for account (the one that appears on top of changing 6-digit code). According https://github.com/google/google-authenticator/wiki/Key-Uri-Format it should go like this: `Company: company.com/me@foo.com`

**Comment by coolaj86** [comment]
See https://github.com/Daplie/node-authenticator/blob/master/authenticator.js#L60

Here's a live demo in the browser:

* https://daplie.github.io/browser-authenticator/ [and code on github](https://github.com/Daplie/browser-authenticator)

Scroll down and you can put in the values you want and then click "Regenerate" to update the URI string and the QRCode.

You can even use the Authy App to test it on your own phone.

Here's the corresponding node example:  https://github.com/Daplie/node-authenticator

**Comment by ovaris** [comment]
Also with live demo you posted, there is no Label when using google Authenticator.
See examples here:

With label:
![image](https://cloud.githubusercontent.com/assets/2553533/11089660/38f45c6a-8874-11e5-95b1-aff6bf27bbc7.png)

Without:
![image](https://cloud.githubusercontent.com/assets/2553533/11089671/4c9b9eb8-8874-11e5-9bb4-01c9438328fa.png)

**Comment by robbo5899** [comment]
I know this is old but for anyone interested adding &issuer=Google to the otpauth url before creating the QRCode would set the label to Google.

**Comment by mikepb** [comment]
`issuer` is now an option to `otpauthURL()`
