### ISSUE TITLE
use notp instead of own implementation

### ISSUE THREAD

**Issue by coolaj86** [speakeasyjs/speakeasy#42]
The notp module lacks some of the features of this module, but the code surrounding the core hotp / totp is cleaner and more idiomatic to node.js.

Would you accept an api-compatible rewrite based on notp? If so I would be willing to do that.

**Comment by coolaj86** [comment]
[Node Authenticator](https://github.com/Daplie/node-authenticator)
================

I wrote [Node Authenticator](https://github.com/Daplie/node-authenticator) as a replacement for SpeakEasy. It uses node's native [crypto](https://nodejs.org/api/crypto.html) module and [notp](https://github.com/guyht/notp).

* https://github.com/Daplie/node-authenticator

**Comment by mikepb** [comment]
Thank you for the suggestion. Speakeasy 2.0 was rewritten to be more idiomatic to node.js.
