### ISSUE TITLE
Publish updated SpeakEasy

### ISSUE THREAD

**Issue by connor4312** [speakeasyjs/speakeasy#46]
Glad to see the changes from #21 and #33 were merged in! However, the npm version has not yet been bumped from 1.0.3 that was published three years ago. It'd be great to see a `1.0.4` :smile:

**Comment by markbao** [comment]
Thanks @connor4312. Bumped version in d27a8a20f9bd874f5d4ecc07dcadb50ce574a5a0 and published to npm. We're also working on a 2.0 in #44 that will incorporate many of those changes.

**Comment by connor4312** [comment]
Great, thanks!
