### ISSUE TITLE
Always getting speakeasy.totp.verify(options) as false

### ISSUE THREAD

**Issue by developerrajtomar** [speakeasyjs/speakeasy#52]
Hi All,

I'm trying to validate otp using speakeasy. I'm able to generate otp and validate otp within the same request. But whenever I'm trying to validate otp in two phases like: Generate OTP in one step, and then Validate OTP in second step. I'm always getting verify as false.

Below is the code that I'm using for validating the OTP. Please let me know what is the wrong in it.

var express = require('express');
var router = express.Router();
var speakeasy = require('speakeasy');

router.route('/generateotp').post(function(req, res){
	var userid= req.body.userid;
	var secret = speakeasy.generateSecret({length: 20});
	var token = speakeasy.totp({
	  secret: secret.base32,
	  encoding: 'base32'
	});
});

router.route('/validateotp').post(function(req, res){
	var userToken= req.body.code;
	var verified = speakeasy.totp.verify({
	    secret: MY_PREVIOUSLY_GENERATED_SECRET
	    encoding: 'base32',
            token: userToken
        });
        console.log(verified);
});

module.exports = router;

In the above code, Why I'm always getting verified as false on /validateotp request?

**Comment by mikepb** [comment]
You may be experiencing clock skew. Try setting the `window` option:

```js
router.route('/validateotp').post(function(req, res){
  var userToken= req.body.code;
  var verified = speakeasy.totp.verify({
    secret: MY_PREVIOUSLY_GENERATED_SECRET
    encoding: 'base32',
    token: userToken,
    window: 2
  });
  console.log(verified);
});
```

With a default time-step of 30 seconds, a `window` of 2 should accept tokens generated within ± 60 seconds of the server time.

**Comment by developerrajtomar** [comment]
Thanks for your reply.

I've already played around time, window, step, counter and all available options and getting same result.

so far I've used values till time: 1453853945, step: 240, window: 100, and counter: 123

**Comment by mikepb** [comment]
Seems to work fine without Express.

Most often when I run into these kinds of bugs, something isn't getting passed from the browser to the server. Could you provide more information about your webapp? What does the `req.body.code` look like (any extra spaces or characters will fail verification)?

```js
> var speakeasy = require('speakeasy')
undefined
> 
> var secret = speakeasy.generateSecret({
...   length: 20
... });
undefined
> 
> var token = speakeasy.totp({
...   secret: secret.base32,
...   encoding: 'base32',
... });
undefined
> 
> speakeasy.totp.verify({
...   secret: secret.base32,
...   encoding: 'base32',
...   token: token,
... });
true
> 
> // Wait 1 second...
undefined
> 
> speakeasy.totp.verify({
...   secret: secret.base32,
...   encoding: 'base32',
...   token: token,
... });
true
> 
> speakeasy.totp.verify({
...   secret: secret.base32,
...   encoding: 'base32',
...   token: token,
...   window: 2,
... });
true
> 
> // Try with fixed values.
undefined
> 
> token = speakeasy.totp({
...   secret: secret.base32,
...   encoding: 'base32',
...   time: 1453853945,
...   step: 240,
...   window: 100,
...   counter: 123,
... });
'700914'
> 
> speakeasy.totp.verify({
...   secret: secret.base32,
...   encoding: 'base32',
...   token: token,
...   time: 1453853945,
...   step: 240,
...   window: 100,
...   counter: 123,
... });
true
> 
```

**Comment by developerrajtomar** [comment]
Hi Sir,

Thanks for replying again. req.body is the body or entire data that is
passed to a particular url via CURL, or Browser request.

My webapp is a mobile api . That I've built in nodejs, expressjs,mongoose
and mongodb. Now at some point of time I need otp generation and
validation. Those two routes methods provide that functionality.

Thanks

**Comment by developerrajtomar** [comment]
Without Express means inst

**Comment by developerrajtomar** [comment]
Sorry for reopening the issue, it was closed by mistake.

Without Express means in the same request right? But I need it to work on multiple requests like above. So please let me know that will this module work for me or I've to migrate to another module.

**Comment by mikepb** [comment]
Have you taken a look at the Speakeasy Demo?
https://github.com/speakeasyjs/speakeasy-demo

I tried it using Google Authenticator and it worked flawlessly.

**Comment by developerrajtomar** [comment]
Thanks for this suggestion, this work finely for me too, but the previous one was not working for me. Now as this 

> **"speakeasy.time"**

 method is not available in the documentation of **speakeasy** module on npm and github. So can you please elaborate the **_functionality_** and **_arguments_** of this **"speakeasy.time"** method that I can use in my application.

Thanks

**Comment by mikepb** [comment]
speakeasy.time is an alias for speakeasy.totp

**Comment by developerrajtomar** [comment]
ok, in that case do you've some logic behind that **speakeasy.time** is working fine but **speakeasy.totp** is not working. Why it is?

**Comment by mikepb** [comment]
There is no logic behind your statement. `speakeasy.time` is the same as `speakeasy.totp`.

https://github.com/speakeasyjs/speakeasy/blob/master/index.js#L297

```js
// Alias time() for totp()
exports.time = exports.totp;
```

**Comment by mikepb** [comment]
```js
var debug = require('debug')('issue52')
var crypto = require('crypto')
var bodyParser = require('body-parser')
var express = require('express')
var speakeasy = require('speakeasy')

var TEST_SECRET = crypto.randomBytes(20)
var TOTP_OPTIONS = {
  step: 30, // 30 second time step
  window: 2 // validate tokens ± 60 seconds
}
var TOTP_PARAM = 'code'

function totp (req, res, next) {
  debug('totp')
  if (!req.totp) req.totp = {}
  if (!res.totp) res.totp = {}
  next()
}

function fetchUserSecret (req, res, next) {
  debug('fetchUserSecret', TEST_SECRET)
  req.totp.secret = TEST_SECRET
  next()
}

function generateCode (req, res, next) {
  var options = {secret: req.totp.secret}
  Object.assign(options, TOTP_OPTIONS)
  debug('generateCode', options)
  res.totp.token = speakeasy.totp(options)
  next()
}

function validateCode (req, res, next) {
  var options = {secret: req.totp.secret, token: req.body[TOTP_PARAM]}
  Object.assign(options, TOTP_OPTIONS)
  res.totp.valid = speakeasy.totp.verify(options)
  debug('validateCode', options, res.totp.valid)
  next()
}

function displayCode (req, res) {
  debug('displayCode', res.totp.token)
  res.send(res.totp.token)
}

function displayResult (req, res) {
  var response = res.totp.valid ? 'OK' : 'INVALID TOKEN'
  debug('displayResult', response)
  res.send(response)
}

var urlencodedParser = bodyParser.urlencoded({ extended: false })

var app = express()

app.use(totp)
app.post('/totp/generate',
  urlencodedParser, fetchUserSecret, generateCode, displayCode)
app.post('/totp/validate',
  urlencodedParser, fetchUserSecret, validateCode, displayResult)
app.listen(3000)
```

```sh
npm install debug body-parser express speakeasy
DEBUG=* node issue.js &
SERVER_PID=$!
TOTP_TOKEN=$(sleep 1 && curl -qX POST http://localhost:3000/totp/generate)
curl -qX POST --data-urlencode code=$TOTP_TOKEN http://localhost:3000/totp/validate && echo
kill $SERVER_PID
```

```
$ bash issue.sh 
/Users/mikepb/Desktop
├── body-parser@1.15.2 
├── debug@2.2.0 
├── express@4.14.0 
└── speakeasy@2.0.0 

npm WARN enoent ENOENT: no such file or directory, open '/Users/mikepb/Desktop/package.json'
npm WARN Desktop No description
npm WARN Desktop No repository field.
npm WARN Desktop No README data
npm WARN Desktop No license field.
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +4ms
  express:application set "etag fn" to [Function: wetag] +2ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +1ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/Users/mikepb/Desktop/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use / query +1ms
  express:router:layer new / +1ms
  express:router use / expressInit +0ms
  express:router:layer new / +0ms
  express:router use / totp +1ms
  express:router:layer new / +0ms
  express:router:route new /totp/generate +0ms
  express:router:layer new /totp/generate +0ms
  express:router:route post /totp/generate +1ms
  express:router:layer new / +0ms
  express:router:route post /totp/generate +0ms
  express:router:layer new / +0ms
  express:router:route post /totp/generate +0ms
  express:router:layer new / +0ms
  express:router:route post /totp/generate +0ms
  express:router:layer new / +0ms
  express:router:route new /totp/validate +0ms
  express:router:layer new /totp/validate +0ms
  express:router:route post /totp/validate +0ms
  express:router:layer new / +0ms
  express:router:route post /totp/validate +0ms
  express:router:layer new / +0ms
  express:router:route post /totp/validate +0ms
  express:router:layer new / +0ms
  express:router:route post /totp/validate +0ms
  express:router:layer new / +0ms
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  express:router dispatching POST /totp/generate +783ms
  express:router query  : /totp/generate +1ms
  express:router expressInit  : /totp/generate +1ms
  express:router totp  : /totp/generate +1ms
  issue52 totp +0ms
  body-parser:urlencoded skip empty body +0ms
  issue52 fetchUserSecret +0ms <Buffer 73 3d 5a 78 28 67 5e a0 12 25 4c 0e 70 da 60 61 0a 00 eb 53>
  issue52 generateCode +1ms { secret: <Buffer 73 3d 5a 78 28 67 5e a0 12 25 4c 0e 70 da 60 61 0a 00 eb 53>,
  step: 30,
  window: 2 }
  issue52 displayCode +13ms 361051
100     6  100     6    0     0    177      0 --:--:-- --:--:-- --:--:--   181
  express:router dispatching POST /totp/validate +33ms
  express:router query  : /totp/validate +0ms
  express:router expressInit  : /totp/validate +0ms
  express:router totp  : /totp/validate +0ms
  issue52 totp +0ms
  body-parser:urlencoded content-type "application/x-www-form-urlencoded" +1ms
  body-parser:urlencoded content-encoding "identity" +2ms
  body-parser:urlencoded read body +0ms
  body-parser:urlencoded parse body +16ms
  body-parser:urlencoded parse urlencoding +0ms
  issue52 fetchUserSecret +1ms <Buffer 73 3d 5a 78 28 67 5e a0 12 25 4c 0e 70 da 60 61 0a 00 eb 53>
  issue52 validateCode +1ms { secret: <Buffer 73 3d 5a 78 28 67 5e a0 12 25 4c 0e 70 da 60 61 0a 00 eb 53>,
  token: '361051',
  step: 30,
  window: 2 } true
  issue52 displayResult +0ms OK
OK
```

**Comment by saikatharryc** [comment]
Hi @mikepb, how can I generate an OTP so that it says false in validation after a certain time of generation?

**Comment by mikepb** [comment]
This is what TOTP is designed to do. Take a look at the documentation on how to use the appropriate functions.

**Comment by markbao** [comment]
@saikatharryc, if you let us know how you'd like to use Speakeasy, maybe we can help with how it can be implemented. TOTP tokens will automatically expire after a certain amount of time as @mikepb says, like Google Authenticator. This may or may not be what you want.

**Comment by chinmay43** [comment]
I'm facing the same issue as @developerrajtomar where all attempts to verify the token (tried by increaing window as well) are failing. 
To confirm, I have different API's for generating, getting and verifiying the token and I am not using the QR code implementation.

Generating Secret :- 

`
      secret = speakeasy.generateSecret {length:20}
`

I'm persisting `secret.base32` in my DB and reusing it below.

While getting Token :- 

      token = speakeasy.totp(    
         secret: kiosk.secret    
         encoding: 'base32')

While verifying Token (in a different API call) :- 

     verified = speakeasy.totp.verify(
        secret: kiosk.secret
        encoding: 'base32'
        token: incoming.otp
        window: 2
      )

the `verified` field is always false. Is there anything inherently wrong with my implementation of this module?

**Comment by Mobasher-NetLinks** [comment]
@developerrajtomar Hi, have you solved this problem? I have the same problem.

**Comment by kmahalingpur** [comment]
@developerrajtomar Hi im also facing same issue..can u tell how u solved??

**Comment by roxcity** [comment]
I am also facing this problem, has anyone fixed this issue?

**Comment by AnKlim** [comment]
@markbao I have the same usue as another mens.

**Comment by inakarune** [comment]
I also have this problem. somebody help me!

**Comment by AbdulKhader4123** [comment]
after 4 hours try,this works for me.  

var secret = Speakeasy.generateSecret({ length: 6 });
                 res.send({ "secret": secret.base32 });

             
            async totpgenerate(request,response) { 
              response.send({
                  "token": Speakeasy.time({
                      secret: request.body.secret,
                      encoding: "base32",
                      step:600,//10 mins
                      window:0
                  })
              })
            }
            ,
            async totpvalidate(request,response) { 
              response.send({
                  "valid": Speakeasy.time.verify({
                    secret:request.body.secret,
                    encoding: 'base32',
                    token: request.body.token,
                    step:600,//10 mins
                      window:0
                  })
              })
            }

**Comment by HamzaAitOumghar** [comment]
Hi, I am also facing this problem, I already tried all the solutions, but the problem still occurs has anyone fixed this issue?

```
const secret = "AZAD22113ADASDJQF";

const token = speakeasy.totp({
      secret: secret,
      encoding: "ascii",
      step: 600,
    });

 const isValid = speakeasy.totp.verify({
        secret: secret,
        token: code,
        encoding: "ascii",
        window: 2,
      });
```

**Comment by rakshitshah94** [comment]
It is not working for me! Any solutions for this bug?

**Comment by nitrostack** [comment]
changing "totp" to "true" also solved mine

**Comment by pedropresotti** [comment]
I was facing the same problem. Turns out the issue was the qrcode generated from the secret. If you are using npm qrcode, use the function:

const generateQR = async text => {

	try {
		const qrCode = await QRCode.toDataURL(text);
		return qrCode;
	} catch (err) {
		throw err;
	}
}

**Comment by truyenh20** [comment]
The following option params **need to be the same** for speakeasy.time() and speakeasy.time.verify():
      **step** (default 30s), **encoding** (default "ascii"), and **algorithm** (default "sha1")

Example:

**Step1: Generate a secret**:
     ` const secret = speakeasy.generateSecret({ length: 6 });`
      
      This generates a secret as below:
      secret: {
        ascii: 'rxG^g?',
        hex: '7278475e673f',
        base32: 'OJ4EOXTHH4',
        otpauth_url: 'otpauth://totp/SecretKey?secret=OJ4EOXTHH4'
      },

**Step2: Generate token:**
```
    const totpOptions = {
      secret: secret.base32,
      step: 300,
      encoding: "base32",
      algorithm: "sha256"
    }
    const confirmCode = speakeasy.time(totpOptions)
```

**Step3: Verify code:**
```
    const verifyOptions = {
      secret: secret.base32,
      step: 300,
      encoding: "base32",
      algorithm: "sha256",
      token: confirmCode
    }
    const verified =  speakeasy.time.verify(verifyOptions)
```

**Comment by lotusdg** [comment]
Сheck your data encoding for otpauthURL and verify (base32|ascii etc)

**Comment by lawrencevds** [comment]
@lotusdg you are my hero :)
