### ISSUE TITLE
Error on npm install?

### ISSUE THREAD

**Issue by knoxcard** [speakeasyjs/speakeasy#59]
When I run this command on my Debian box:
npm install --save speakeasy

I get the following errors below?  Never have an issue with an npm install, is it just me?

npm ERR! addLocal Could not install /usr/local/nginx/node_services/node_modules/speakeasy
npm ERR! Linux 4.7.0-x86_64-linode72
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "speakeasy"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! path /usr/local/nginx/node_services/node_modules/speakeasy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/nginx/node_services/node_modules/speakeasy'
npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/nginx/node_services/node_modules/speakeasy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/nginx/node_services/npm-debug.log
root@indoworld:/usr/local/nginx/node_services# npm install --save speakeasy
npm ERR! addLocal Could not install /usr/local/nginx/node_services/node_modules/speakeasy
npm ERR! Linux 4.7.0-x86_64-linode72
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "speakeasy"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! path /usr/local/nginx/node_services/node_modules/speakeasy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

**Comment by mikepb** [comment]
Looks like the node_modules/speakeasy directory doesn’t exist. Do you have the proper permissions?

**Comment by knoxcard** [comment]
I was able to install it by adding the -g global option, but it will not 
work without it.  Oh well, works for me!

*npm install --save speakeasy -g
*
