### ISSUE TITLE
urls generated by speakeasy.otpauthURL do not match the once generated by generateSecret

### ISSUE THREAD

**Issue by id0Sch** [speakeasyjs/speakeasy#60]
the issue is that generateSecret runs the name property through encodeURIComponent and otpauthURL does not.
would you like me to open a PR to either fix it or change the documentation to show this?
thanks!

**Comment by railsstudent** [comment]
Yeah, I notice that too. Furthermore,  counter passed to otpauthURL is not appended to query; therefore, the counter in server side does not match the counter in google authenticator app.

**Comment by mikepb** [comment]
Changing the behavior of `generateSecret` will break backwards compatibility. @markbao Should this bugfix bump Speakeasy to 3.0?

@railsstudent Omitting `counter` in the `otpauthURL` output is definitely a bug. Could you open a new issue for it? Pull request appreciated!

**Comment by id0Sch** [comment]
I honestly think otpauthURL should change, but it's the same breakage

**Comment by railsstudent** [comment]
I can open a new issue.
