### ISSUE TITLE
Verification keeps failing for HEX and Base32 only ASCII working fine

### ISSUE THREAD

**Issue by tonespy** [speakeasyjs/speakeasy#65]
I've been trying to understand the module for house now, but couldn't get to understand what is going on. I followed the steps in the documentation, and it still isn't verifying. This is my code

	function getPublicKey() {

		var secret = speakeasy.generateSecret({length: 25});
		var base32Secret = secret["base32"];
		console.log("Secret: ", base32Secret);

		var token = speakeasy.totp({base32Secret, encoding: 'base32', window: 6});

		console.log("MainToken: ", token);

		var tokenValidates = speakeasy.totp.verify({
		  secret: base32Secret,
		  encoding: 'base32',
		  token: token,
		  window: 6
		});

		console.log("TokenValidate: ", tokenValidates);

		var newTokenValidates = speakeasy.totp.verify({
		  secret: base32Secret,
		  encoding: 'base32',
		  token: '1234356'
		});

		console.log("NewTokenValidate: ", newTokenValidates);
	}

And, this is my response:

	Secret:  IJQSCWS3KJHE2KLCJA4UOUJYONNHQWTPHIXTSIJM
	MainToken:  615020
	TokenValidate:  false
	NewTokenValidate:  false

And then, I tried for ASCII and it works fine

	function getPublicKey() {

		var secret = speakeasy.generateSecret({length: 25});
		var acsiiSecret = secret["ascii"];
		console.log("Secret: ", acsiiSecret);

		var token = speakeasy.totp({secret: acsiiSecret});

		console.log("MainToken: ", token);

		var tokenValidates = speakeasy.totp.verify({
		  secret: acsiiSecret,
		  encoding: 'ascii',
		  token: token
		});

		console.log("TokenValidate: ", tokenValidates);

		var newTokenValidates = speakeasy.totp.verify({
		  secret: acsiiSecret,
		  encoding: 'ascii',
		  token: '1234356'
		});

		console.log("NewTokenValidate: ", newTokenValidates);
	}

And the result:

	Secret:  fm:Scz4n7TDlZXA/}0OPxR3[<
	MainToken:  228114
	TokenValidate:  true
	NewTokenValidate:  false

**Comment by railsstudent** [comment]
There is coding error in line 4 of your sample code.
You forgot to specify property key name 'secret' before base32Secret variable.

var token = speakeasy.totp({secret: base32Secret, encoding: 'base32', window: 6});

After I do it, verify method returns true.

**Comment by railsstudent** [comment]
This issue occurs because the required fields are not checked in hotpVerify, totpVerify, totp and hotp functions. I can make a PR to check the required fields and throw error accordingly.

**Comment by railsstudent** [comment]
Can I close this issue because it is coding error on the author?

**Comment by shaddyhm** [comment]
This issue above is valid and still going. I used "base32" the token was not validating. Once I switched to the default, which I believe "ASCII," it worked with no problems. I encourage you to take another look at the issue. Thank you.

**Comment by railsstudent** [comment]
can u provide the code u use?

**Comment by shaddyhm** [comment]
I can't provide you with the exact code, but here is sort of what I did. Here is the mindboggling part! It worked for some time, but it fails a lot of the time. 

```
function generateSecret(){
    return speakeasy.generateSecret({length: 20});
} 

function getCodeToken(secret: Key) {
    return speakeasy.totp({
        secret: secret.base32,
        encoding: 'base32'
    });
}

function isCodeValid(secret: string, code: number | string){
    return speakeasy.totp.verify({
        secret: secret,
        encoding: 'base32',
        token: code.toString()
    });
}

let secret = generateSecret();
let token = getCodeToken(secret);
let isVerified = isCodeValid(user.speakeasySecret, req.body.code);
```
If the code sent by the user is correct, the isVerified is suppose to be true, but that is almost always not the case on my end. Let me know if I am doing something wrong here. Thank you.
