### ISSUE TITLE
Default values of otpAuthURL are inconsistent with the documentation in README.md

### ISSUE THREAD

**Issue by railsstudent** [speakeasyjs/speakeasy#71]
In README.md,  the default values of algorithm, digits, period are sha1, 6 and 30 respectively.  In code, no value is assigned and it works in google authenticator app for now because these parameters are ignored.

In code, the default value of encoding is ascii but README.md leaves the default value blank,
I would like to make the doc and code consistent, so the code does what the documentation says.

**Comment by markbao** [comment]
@railsstudent, PR #74 resolves this, correct?

Sharp eye - thanks for being on top of this.

**Comment by railsstudent** [comment]
yes. #74 resolves this.

**Comment by mikepb** [comment]
Closing as resolved.
