### ISSUE TITLE
Does Not Match Test Vectors for sha512 and sha256

### ISSUE THREAD

**Issue by mslosarek** [speakeasyjs/speakeasy#76]
speakeasy does not currently match the test vectors as described here: 
https://tools.ietf.org/html/rfc6238#appendix-B

For it to work correctly, the secret needs to be "12345678901234567890123456789012" for sha256 and "1234567890123456789012345678901234567890123456789012345678901234" for sha512

**Comment by markbao** [comment]
Looping in @mikepb.

@mslosarek, I'm not exactly sure where to find those secrets. Are you referring to the linked table or the example implementation in the RFC?

**Comment by mslosarek** [comment]
```
speakeasy.totp({
    "secret": "12345678901234567890",
    "encoding": "ascii",
    "time": 59,
    "algorithm": "sha256",
    "digits": 8
})```
returns "32247374" not "46119246"

```
speakeasy.totp({
    "secret": "12345678901234567890123456789012",
    "encoding": "ascii",
    "time": 59,
    "algorithm": "sha256",
    "digits": 8
})```
returns "46119246" as expected.

The library is not padding the secret correctly, the spec repeats the secret, it appears you might be null padding.

**Comment by markbao** [comment]
Ah, I see what you're saying now. Thanks for the report - looking into it.

**Comment by mslosarek** [comment]
Created a pull request #77 to handle the padding issue in the secret.
