### ISSUE TITLE
Run Standard formatter prior to releasing 3.0

### ISSUE THREAD

**Issue by mikepb** [speakeasyjs/speakeasy#78]
Use [standard](http://standardjs.com) to format source code, require all future updates to use standard format. Reduces chances of superfluous code changes, such as white-space, slowing down the review process.

**Comment by markbao** [comment]
Should we have a GitHub PR check for Standard linting?

Also, we're using Semistandard (Standard + semicolons), not sure if there's any interest in changing it.

**Comment by mikepb** [comment]
I didn’t that was a thing! Semistandard linting would work.

**Comment by markbao** [comment]
Sounds good. I made sure our 2.0 release passed Semistandard, but likely not the code since.
