### ISSUE TITLE
Missing dependencies in package.json

### ISSUE THREAD

**Issue by RazZziel** [speakeasyjs/speakeasy#84]
[index.js](https://github.com/speakeasyjs/speakeasy/blob/master/index.js#L4) imports the `crypto`, `url` and `util` dependencies, but [package.json](https://github.com/speakeasyjs/speakeasy/blob/master/package.json#L40) only includes `base32`

**Comment by railsstudent** [comment]
It is not an issue. 
crypto, util and url are built-in modules in node 0.10.0. No need to include dependencies in package.json.
https://nodejs.org/docs/latest-v0.10.x/api/util.html

**Comment by RazZziel** [comment]
Hmmm, thanks! Then the problem must be I'm using MeteorJS NPM integration incorrectly.
