### ISSUE TITLE
How to export keys to the user?

### ISSUE THREAD

**Issue by subversivo58** [speakeasyjs/speakeasy#93]
Excuse me if I'm wrong, most likely I did not understand the operation.

How do I export a set of keys for recovery?

I'm lost on the following point:

**1:**
The user creates an account in the application (automatically saves a [base32] key to the database)

**2:**
The user logs in and activates the use of 2FA (at this point a qrCode is generated for it to scan and confirm that the user is using a compatible application - if everything happens well, in fact 2FA is activated)

**3:**
When the user makes a new login or an important function like account email update or password the verification code is required (everything works well here)

From this point on in loss cases I'm not sure how it works, I saw some generators export a set of keys ... how does this work in this library? should I offer the option to export the entire secret key (base32) generated in step 2?

Following this reasoning works, I offer the option to upload the token (base32) and verify if it exists in the database, if there is a qrCode for the user to scan again and have access to the application.

But I do not know if this is the most appropriate option and if there is some risk of security included that I am not observing at this moment.

**Comment by railsstudent** [comment]
I do not think speakeasy supports recovery key yet.
@markbao @mikepb  Is my understanding correct?

**Comment by jakelee8** [comment]
Recovery keys are not part of the HOTP/TOTP RFCs, not part of the OTP standard, and not supported by speakeasy.

I would not recommend exposing a feature to verify if an OTP secret is valid. You're essentially giving hackers a way to guess the OTP secret.

Most sites I've used with 2FA offer to text a phone number with the OTP code as a backup. Some services, like GitHub and Google, give users a set of [one-time recovery codes](https://help.github.com/articles/recovering-your-account-if-you-lost-your-2fa-credentials/).

How you implement 2FA recovery depends on your requirements.

**Comment by subversivo58** [comment]
Hum ok ... I think I understand, supply recovery codes should be treated as an application routine with care not to expose the secret key (base32). In short recovery codes should not be derived from this key?

For the time being I thought of generating a set (10 keys) randomly generated with uuid and stored in the database at user input.

If he loses his 2FA application he can use one of these (10) keys, but that would skip the code verification step.

![signin-2](https://user-images.githubusercontent.com/6475273/30815610-13aa3dc6-a1ea-11e7-81de-af940489c093.PNG)

![signin-3](https://user-images.githubusercontent.com/6475273/30815917-ebb1f312-a1ea-11e7-91e3-76761f39ff60.PNG)

Although it may be applicable I wonder if there should be an explanation about this in this lib because apparently if the user loses access to the application 2FA also loses access to the account irremediably. Is there any work for this purpose that can complement this lib?

**Comment by subversivo58** [comment]
I think I understood, a recovery system should be handled outside the scope of this lib and should not use, reference or derive from the secret key (base32).

Thanks for the help, closing.
